# Generated by Django 5.1.4 on 2024-12-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winebottle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winebottle',
            name='food_pairing',
            field=models.TextField(blank=True, help_text='Comma separated, e.g. red meat, cheese', null=True),
        ),
        migrations.AlterField(
            model_name='winebottle',
            name='link',
            field=models.URLField(blank=True, help_text="Unique URL for each wine bottle (could be a link to the wine maker's website)", null=True),
        ),
        migrations.AlterField(
            model_name='winebottle',
            name='taste',
            field=models.TextField(blank=True, help_text='Comma separated, e.g., plum, tobacco', null=True),
        ),
    ]
