# Generated by Django 5.1.4 on 2024-12-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0002_alter_winebottle_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winebottle',
            options={'ordering': ['name', 'year', 'count_in_winecellar']},
        ),
        migrations.AlterModelOptions(
            name='winemaker',
            options={'ordering': ['name']},
        ),
    ]
